apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.component }}-service
  labels:
    system: {{ .Values.system }}
spec:
  workspaces:
  - name: maven-repo
  - name: maven-settings

  params:
    - default: https://github.com/{{ .Values.domain }}/{{ .Values.system }}-{{ .Values.component }}-service
      name: git-url
      type: string
      description: "component source Git pepository"
    - default: main
      name: git-revision
      type: string
      description: "component source Git revision"
    - default: ./src/main/docker/Dockerfile
      name: dockerfilePath
      type: string
      description: "path to Dockerfile"
    - default: {{ .Values.image.registry }}/{{ .Values.system }}-build/{{ .Values.component }}
      name: image
      type: string
      description: "container image"
    - default: latest
      name: version
      type: string
      description: "release version"

  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: maven-repo

  - name: build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["clone"]
    params:
    - name: GOALS
      value: ["compile"]
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: package
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["build"]
    params:
    - name: GOALS
      value: 
        - package
        - -DskipTests
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: build-container-image
    runAfter: ["package"]
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: maven-repo
    params:
    - name: IMAGE
      value: $(params.image):$(params.version)
    - name: DOCKERFILE
      value: $(params.dockerfilePath)

  - name: deploy-to-dev
    runAfter: 
      - build-container-image 
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
    - name: SCRIPT
      value: oc rollout restart deployment/{{ .Values.component }} -n {{ .Values.system }}-dev


