apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: create-promote-pull-request
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to update image digest in a Git repo using the kustomize
  params:
    - name: GIT_REPOSITORY
      type: string
    - name: COPY_FROM_PATH
      type: string
    - name: COPY_TO_PATH
      type: string
  workspaces:
    - description: The workspace consisting of maven project.
      name: maven-repo
  results:
    - name: branch_name
      description: The branch name used for pull-request
  steps:
    - name: promote
      image: mirror.gcr.io/alpine/git:v2.26.2
      workingDir: $(workspaces.maven-repo.path)
      script: |
        set -x
        rm -rf pull-request-workdir
        git clone $(params.GIT_REPOSITORY) pull-request-workdir
        cd pull-request-workdir

        branch_name=staging
        git checkout -b $branch_name
        staging_exists=`git show-ref refs/heads/staging`
        if [ -n "$staging_exists" ]; then
          echo 'branch exists!'
        elif
          git checkout -b staging
          git push origin +staging
        fi
        echo -n "$branch_name" > $(results.branch_name.path)

        git status
        git add .
        git commit -m "[$(context.taskRun.name)] Promotion from dev to staging (qa)"

        git push origin $branch_name