---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component }}-api-workspace
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
