apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    system: {{ .Values.system }}
    component: {{ .Values.component }}
    'backstage.io/kubernetes-id': {{ .Values.component }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      system: {{ .Values.system }}
      component: {{ .Values.component }}
  template:
    metadata:
      labels:
        system: {{ .Values.system }}
        component: {{ .Values.component }}
    spec:
      containers:
        - name: {{ .Values.component }}
          image: "{{ .Values.image.registry }}/{{ .Values.system }}-build/{{ .Values.component }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: AB_JOLOKIA_AUTH_OPENSHIFT
              value: cn=hawtio-online.hawtio.svc
            - name: AB_JOLOKIA_OPTS
              value: caCert=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
