{{- if eq .Values.environment.name .Values.build.environment }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.delivery.project | quote }}
  namespace: {{ .Values.delivery.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    contract-first-idp.github.io/domain: {{ .Values.domainName | quote }}
    contract-first-idp.github.io/system: {{ .Values.systemName | quote }}
    contract-first-idp.github.io/project-scope: system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Contract-First IDP leaf Applications for the {{ .Values.systemName }} System in the {{ .Values.domainName }} Domain.
  sourceRepos:
    - {{ .Values.delivery.charts.repository | quote }}
    - {{ .Values.systemRepository.url | quote }}
  destinations:
    - server: {{ .Values.delivery.destinationServer | quote }}
      namespace: {{ printf "%s*" .Values.systemName | quote }}
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - {group: "", kind: ConfigMap}
    - {group: "", kind: Service}
    - {group: apps, kind: Deployment}
    - {group: batch, kind: Job}
    - {group: image.openshift.io, kind: ImageStream}
    - {group: postgres-operator.crunchydata.com, kind: PostgresCluster}
    - {group: route.openshift.io, kind: Route}
    - {group: tekton.dev, kind: Pipeline}
    - {group: triggers.tekton.dev, kind: EventListener}
    - {group: triggers.tekton.dev, kind: TriggerBinding}
    - {group: triggers.tekton.dev, kind: TriggerTemplate}
{{- end }}
