{{- if eq .Values.environment.name .Values.build.environment }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apicurio-client
  namespace: {{ .Values.systemName }}{{ .Values.environment.namespaceSuffix }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: {{ .Values.domainName }}-publishers}
  target: {name: apicurio-client, creationPolicy: Owner, deletionPolicy: Delete}
  dataFrom: [{extract: {key: {{ .Values.domainName }}-apicurio}}]
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-client
  namespace: {{ .Values.systemName }}{{ .Values.environment.namespaceSuffix }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef: {kind: ClusterSecretStore, name: {{ .Values.domainName }}-publishers}
  target: {name: microcks-client, creationPolicy: Owner, deletionPolicy: Delete}
  dataFrom: [{extract: {key: {{ .Values.domainName }}-microcks}}]
{{- end }}
