{{- range $env := .Values.environments }}
{{ if ne $env "build" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.system }}-app-registry-access-{{ $env }}
  namespace: {{ $.Values.system }}-build
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ $.Values.system }}-{{ $env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.system }}-pipeline-rollout-access
  namespace: {{ $.Values.system }}-{{ $env }}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ $.Values.system }}-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
{{- end }}
{{- end }}
